


all: ascii dado generate ordena pause primos

pause:
	gcc pause.cpp -o pause

ascii:
	gcc ascii.cpp -o ascii

dado:
	gcc dado.cpp -o dado

primos:
	gcc primos.cpp -o primos

series:
	gcc series.cpp -o series

generate:
	gcc generate.cpp -o generate

ordena:
	gcc ordena.cpp -o ordena -lrt

clean:
	rm -f pause ascii dado primos series generate ordena 
